apiVersion: {{ include "statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "rudderstack.fullname" . }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rudderstack.fullname" . }}
  replicas: {{ .Values.global.backendReplicaCount }}
  selector:
    matchLabels:
      {{- include "rudderstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rudderstack.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/rudder-config: {{ .Files.Get "rudder-config.toml" | sha256sum }}
        checksum/rudder-bigquery-credentials: {{ .Files.Get "bigquery-credentials.json" | sha256sum }}
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "backend.fullname" . }}-config
          name: backend-config-volume
        {{- if .Values.telegraf_sidecar.enabled}}
        - name: telegraf
          configMap:
            defaultMode: 420
            name: {{ include "telegraf-sidecar.fullname" . }}-config
        {{- end }}
        {{- if .Values.gcpCredentialSecret.enabled }}
        - name: google-application-credentials
          secret:
            defaultMode: 420
            secretName: {{ include "rudderstack.fullname" . }}-gcp
        {{- end }}
      containers:
      - name: {{ include "backend.name" . }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.version }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        volumeMounts:
        - mountPath: {{ .Values.backend.config.mountPath }}
          name: backend-config-volume
        - mountPath: {{ .Values.backend.persistence.mountPath }}
          name: {{ include "backend.name" . }}-data
        {{- if .Values.gcpCredentialSecret.enabled }}
        - mountPath: {{ .Values.gcpCredentialSecret.mountPath }}
          name: google-application-credentials
        {{- end }}
        ports:
          - name: backend
            containerPort: {{ .Values.backend.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.service.targetPort }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        env:
          {{- if .Values.backend.extraEnvVars }}
            {{- .Values.backend.extraEnvVars | toYaml | nindent 10 }}
          {{- end }}
          - name: CONFIG_BACKEND_TOKEN
            value: {{ .Values.rudderWorkspaceToken }}
            {{- if .Values.backend.controlPlaneJSON }}
          - name: RSERVER_BACKEND_CONFIG_CONFIG_FROM_FILE
            value: "{{ .Values.backend.controlPlaneJSON }}"
          - name:  RSERVER_BACKEND_CONFIG_CONFIG_JSONPATH
            value: "{{ .Values.backend.config.mountPath }}/workspaceConfig.json"
            {{- end}}
          - name: DEST_TRANSFORM_URL
            value: "http://{{ include "transformer.fullname" . }}:{{ .Values.transformer.service.port}}"
          - name: COMPUTE_DB_HOST_IN_K8S
            {{- if .Values.external_postgresql.enabled }}
            value: "false"
            {{ else }}
            value: "true"
            {{- end }}
          - name: POSTGRES_POD_NAME
            value: "{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}"
          - name: POSTGRES_HEADLESS_SVC
            value: "{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}-headless"
          - name: JOBS_DB_HOST
            {{- if .Values.external_postgresql.enabled }}
            value: "{{ .Values.external_postgresql.postgresqlHost }}"
            {{ else }}
            value: "This is expected to be set by docker entrypoint script"
            {{- end }}
          - name: JOBS_DB_USER
            {{- if .Values.external_postgresql.enabled }}
            value: "{{ .Values.external_postgresql.postgresqlUsername }}"
            {{ else }}
            value: "{{ .Values.postgresql.postgresqlUsername }}"
            {{- end }}
          - name: JOBS_DB_PORT
            {{- if .Values.external_postgresql.enabled }}
            value: "{{ .Values.external_postgresql.postgresqlPort }}"
            {{ else }}
            value: "{{ .Values.postgresql.service.port }}"
            {{- end }}
          - name: JOBS_DB_DB_NAME
            {{- if .Values.external_postgresql.enabled }}
            value: "{{ .Values.external_postgresql.postgresqlDatabase }}"
            {{ else }}
            value: "{{ .Values.postgresql.postgresqlDatabase }}"
            {{- end }}
          - name: JOBS_DB_PASSWORD
            {{- if .Values.external_postgresql.enabled }}
            value: "{{ .Values.external_postgresql.postgresqlPassword }}"
            {{ else }}
            value: "{{ .Values.postgresql.postgresqlPassword }}"
            {{- end }}
          {{- if .Values.external_postgresql.enabled }}
          - name: JOBS_DB_SSL_MODE
            value: "{{ .Values.external_postgresql.postgresqlSslMode }}"
          {{- end }}
          - name: INSTANCE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBE_NAMESPACE
            value: {{ .Release.Namespace }}
        command: ["/docker-entrypoint.sh"]
        args: ["/bin/sh","-c","/wait-for $JOBS_DB_HOST:$(JOBS_DB_PORT) -- /rudder-server"]
        {{- if .Values.telegraf_sidecar.enabled}}
      - name: {{ include "telegraf-sidecar.name" .}}
        image: "{{ .Values.telegraf_sidecar.image.repo }}:{{ .Values.telegraf_sidecar.image.tag }}"
        imagePullPolicy: {{ default "" .Values.telegraf_sidecar.image.pullPolicy | quote }}
        env:
          - name: KUBE_NAMESPACE
            value: {{ .Release.Namespace }}
        command: ["telegraf"]
        args: ["--config", "{{.Values.telegraf_sidecar.config.mountPath}}/telegraf.conf"]
        {{- if .Values.telegraf_sidecar.resources }}
        resources:
        {{- toYaml .Values.telegraf_sidecar.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: telegraf
            mountPath: {{.Values.telegraf_sidecar.config.mountPath}}
  {{- end}}


  volumeClaimTemplates:
    - metadata:
        name: {{ include "backend.name" . }}-data
    {{- with .Values.backend.persistence.annotations }}
      annotations:
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
      spec:
        storageClassName: {{ .Values.global.storageClass }}
        accessModes:
        {{- range .Values.backend.persistence.accessModes }}
         - {{ . | quote }}
        {{- end }}
        resources:
          requests:
           storage: {{ .Values.backend.persistence.size | quote }}
